apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 80
